# Site settings
title: Mohamed Amin
description: Cloud Solution Architect
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mohamed Amin
user_description: I am a Data Solution Architect. I help companies build secure, reliable, performant and cost-optimized cloud data platforms. I have over 12 years of experience. 
user_title: Data Solution Architect
#email: mauriurraco@gmail.com
#twitter_username: lorem_ipsum
#instagram_username: mauriciourraco7
#facebook_username: mauricio.urraco
linkedin_username: mhamin
github_username:  aminsrc
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

